modules/Car/Http/routes.php
<?php

#Admin
Route::group(['prefix' => 'admin', 'middleware' => ['admin.auth', 'admin.menu.storing'], 'namespace' => 'Modules\Car\Http\Controllers'], function()
{
	Route::group(['prefix' => 'car', 'namespace' => 'Admin'], function() {
		Route::resource('transport', 'TransportController');
		Route::resource('transport_type', 'TransportTypeController');
		Route::resource('mark', 'MarkController');
		Route::controller('model', 'ModelController',
			[   'getShow' => 'admin.car.model.show',
				'getCreate' => 'admin.car.model.create',
				'putUpdate' => 'admin.car.model.update',
				'postStore' => 'admin.car.model.store',
				'deleteDestroy' => 'admin.car.model.destroy',
			]
		);
		Route::resource('modification', 'ModificationController');
		Route::resource('motor', 'MotorController');
		Route::resource('lamps', 'MotorLampsController', ['only' => ['edit', 'update']]);
		Route::get('lamps/sync', ['as' => 'admin.car.lamp.sync', 'uses' => 'MotorLampsController@sync']);
		Route::get('catalog/export', ['as' => 'admin.car.catalog.export', 'uses' => 'ExportController@catalog']);
        Route::get('catalog/mark/{id}/export', ['as' => 'admin.car.catalog.mark.export', 'uses' => 'ExportController@mark']);
		Route::post('motors/parent', ['as' => 'admin.car.catalog.motor.parent.update', 'uses' => 'MotorController@parent']);

        Route::resource('question', 'QuestionController');
	});
});

#Front
Route::group(['prefix' => 'catalog', 'namespace' => 'Modules\Car\Http\Controllers\Front'], function()
{
	Route::get('transports', ['as' => 'catalog.transport', 'uses' => 'CatalogController@transports']);
	Route::get('marks/{id}', ['as' => 'catalog.marks', 'uses' => 'CatalogController@marks']);
	Route::get('models/{id}/{transport_id}', ['as' => 'catalog.models', 'uses' => 'CatalogController@models']);
	Route::get('years/{id}', ['as' => 'catalog.years', 'uses' => 'CatalogController@years']);
	Route::get('modifications/{modelId}', ['as' => 'catalog.modifications', 'uses' => 'CatalogController@modifications']);
	Route::get('motors/{id}', ['as' => 'catalog.motors', 'uses' => 'CatalogController@motors']);
	Route::get('lamps/{id}', ['as' => 'catalog.lamps', 'uses' => 'CatalogController@lamps']);
});

Route::post('/sku/search', ['as' => 'sku.search','uses' => 'Modules\Car\Http\Controllers\Front\SkuController@search']);
# API
Route::group(['prefix' => 'api', 'namespace' => 'Modules\Car\Http\Controllers'],
	function () {
		Route::group(['prefix' => 'car', 'namespace' => 'API'], function () {
			Route::controller('transport', 'TransportController');
			Route::controller('mark', 'MarkController');
			Route::controller('model', 'ModelController');
			Route::controller('modification', 'ModificationController');
			Route::controller('motor', 'MotorController');
//			FILTER
			Route::controller('filter', 'FilterController');
		});
	});

modules/Car/Http/Controllers/Admin/QuestionController.php
<?php namespace Modules\Car\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Kris\LaravelFormBuilder\FormBuilder;
use Kris\LaravelFormBuilder\FormBuilderTrait;
use Modules\Car\Entities\CaseQuestion;
use Modules\Car\Forms\QuestionForm;
use Pingpong\Modules\Routing\Controller;

class QuestionController extends Controller
{
	use FormBuilderTrait;

	protected $formBuilder;

    /**
     * QuestionController constructor.
     * @param FormBuilder $formBuilder
     */
	public function __construct(FormBuilder $formBuilder)
	{
		$this->formBuilder = $formBuilder;
	}

	public function index()
	{
		$questions = CaseQuestion::all();

		return View::make('car::admin.question.list', compact('questions'));
	}

	public function edit($id)
	{
		$entity = CaseQuestion::findOrFail($id);
		$form = $this->formBuilder->create(QuestionForm::class, [
			'model' => $entity,
			'novalidate' => '',
			'class' => 'form-horizontal form-label-left',
			'method' => 'PUT',
			'url' => route('admin.car.question.update', ['id' => $entity->id])

		]);
		$backBtnUrl = route('admin.car.question.index');

		$header = 'Edit transport';
		return View::make('car::admin.entity_edit', compact('backBtnUrl','entity', 'form', 'header'));

	}
	public function update($id, Request $request)
	{
		$postData = $request->all();
		$form = $this->form(QuestionForm::class);

		if (!$form->isValid()) {
			return redirect()->back()->withErrors($form->getErrors())->withInput();
		}
		$question = CaseQuestion::findOrFail($id);
		$question->fill($request->all());
		$question->save();

		return redirect()->back()->with('success', 'Entity successfully updated!');
	}

	public function destroy($id, Request $request)
	{
		$motor = CaseQuestion::findOrFail($id);
		$motor->delete();

		return redirect()->back()->with('success', 'Entity successfully deleted!');
	}

	public function create(Request $request)
	{

		$entity = new CaseQuestion();
		$form = $this->formBuilder->create(QuestionForm::class, [
			'model' => $entity,
			'novalidate' => '',
			'class' => 'form-horizontal form-label-left',
			'method' => 'POST',
			'url' => route('admin.car.question.store')

		]);

		$backBtnUrl = route('admin.car.question.index');
		$header = 'Create new transport';
		return View::make('car::admin.entity_edit', compact('backBtnUrl', 'entity', 'form', 'header'));

	}

	public function store(Request $request)
	{
		$form = $this->form(QuestionForm::class);

		// It will automatically use current request, get the rules, and do the validation
		if (!$form->isValid()) {
			return redirect()->back()->withErrors($form->getErrors())->withInput();
		}
		$question = CaseQuestion::create($request->all());

		return redirect()->route('admin.car.question.index')->with('success', 'Question successfully added!');

	}

}

modules/Car/Resources/views/admin/question/list.blade.php
@extends('admin::layouts.master')

@section('content')
    <h1>Questions</h1>
    <div class="col-md-12">
        <div class="col-md-6"></div>
        <div class="text-right col-md-6">
            <a class="btn btn-success" href="{{route('admin.car.question.create')}}">Create</a>
        </div>
    </div>
    <div class="car-types col-md-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Question</h2>

                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Code</th>
                        <th>Message</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($questions as  $question)
                        <tr>
                            <th>{{$question->id}}</th>
                            <td>{{$question->code}}</td>
                            <td>{{$question->message}}</td>
                            <td>
                                <a class="car-entity-edit"
                                   href="{{route('admin.car.question.edit', ['id' => $question->id])}}"><i
                                            class='glyphicon glyphicon-edit'></i></a>
                                <form class="car-entity-delete-form" method="POST"
                                      action="{{route('admin.car.question.destroy', ['id' => $question->id])}}">
                                    <input type="hidden" name="_method" value="delete"/>
                                    <input name="_token" type="hidden" value="{{csrf_token()}}">
                                    <i class='entity-delete glyphicon glyphicon-trash'></i>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <br clear="both"/>
    <div class="clearfix"></div>
@stop

@section('javascript')
    <!-- bootstrap progress js -->
    <script src="{{Module::asset('admin:js/progressbar/bootstrap-progressbar.min.js')}}"></script>
    <script src="{{Module::asset('admin:js/nicescroll/jquery.nicescroll.min.js')}}"></script>
    @include('admin::partials.js.form')
    <!-- form validation -->
    <script type="text/javascript">
        $(document).ready(function () {
            // initialize the validator function
            validator.message['date'] = 'not a real date';

            // validate a field on "blur" event, a 'select' on 'change' event & a '.reuired' classed multifield on 'keyup':
            $('form')
                    .on('blur', 'input[required], input.optional, select.required', validator.checkField)
                    .on('change', 'select.required', validator.checkField)
                    .on('keypress', 'input[required][pattern]', validator.keypress);

            $('.multi.required')
                    .on('keyup blur', 'input', function () {
                        validator.checkField.apply($(this).siblings().last()[0]);
                    });
            $('form').submit(function (e) {
                e.preventDefault();
                $('#html').val($('#editor').html());
                var submit = true;
                // evaluate the form using generic validaing
                if (!validator.checkAll($(this))) {
                    submit = false;
                }

                if (submit)
                    this.submit();
                return false;
            });
        });
    </script>
    <!-- /form validation -->
    <script>
        $('document').ready(function(){
            $('#car-entity-edit').on('click', function(e){
                e.preventDefault();
                if ($('.car-entity-delete-form').length == 0) {
                    $('.x_content h3').each(function (index) {

                        var id = $(this).attr('sid');
                        var html = '&nbsp&nbsp<span>';
                        html += "<a class='edit' href='/admin/car/transport/" + id + "/edit'><i class='glyphicon glyphicon-edit'></i></a>";
                        html += '&nbsp<form class="car-entity-delete-form" method="POST" action="/admin/car/transport/' + id + '">';
                        html += '<i class="entity-delete glyphicon glyphicon-trash"></i>';
                        html += '<input type="hidden" name="id" value="' + id + '" />';
                        html += '<input type="hidden" name="_method" value="DELETE" />';
                        html += '<input type="hidden" name="_token" value="{{csrf_token()}}" />';
                        html += '</form>';
                        html += '</span>';
                        $(this).parent().after(html);

                    });
                }
            });
        });
    </script>
@stop

@section('style')
    <style>
        .car-types {
            margin-top: 50px;
        }
        .x_content h3 {
            float: left;
        }
        .col-md-4 a {
            display: inline-flex;
        }
    </style>
@stop