modules/Storage/Http/routes.php
<?php
#Admin
Route::group([
    'prefix' => 'admin',
    'middleware' => ['admin.auth', 'admin.menu.storing'],
    'namespace' => 'Modules\Storage\Http\Controllers'], function () {
    Route::group(['prefix' => 'storage', 'namespace' => 'Admin'], function () {
        Route::resource('storage', 'StorageController');
        Route::resource('upload', 'UploadController');
        Route::post('storage/mark', ['as' => 'admin.storage.storage.mark', 'uses' => 'StorageController@mark']);
    });
});

Route::get('storage/download/{code}', ['as' => 'front.storage.download', 'uses' => 'Modules\Storage\Http\Controllers\Front\StorageController@download']);

modules/Storage/Entities/File.php
<?php namespace Modules\Storage\Entities;

/**
 * Created by PhpStorm.
 * User: dat
 * Date: 21.01.18
 * Time: 20:22
 */
class File extends \Modules\Cms\Entities\File
{

    const DOWNLOAD_LINK_SALT = 'xxxxxx';

    protected $fillable = [
        'name',
        'title',
        'path',
        'sort',
        'for_storage'
    ];

    public function getDownloadLink() {
        return md5($this->id.self::DOWNLOAD_LINK_SALT);
    }
}

modules/Storage/Http/Controllers/Admin/StorageController.php
<?php namespace Modules\Storage\Http\Controllers\Admin;

use App\Traits\SaveFileTrait;
use Illuminate\Http\Request;
use Modules\Storage\Entities\File;
use Pingpong\Modules\Routing\Controller;
use Illuminate\Support\Facades\View;

class StorageController extends Controller
{

    use SaveFileTrait;

    /**
     * @return mixed
     */
    public function index()
    {
        $files = File::where(['from_storage' => 1])->orderBy('id', 'desc')->paginate(50);
        return View::make('storage::index', compact('files'));
    }

    /**
     * @return mixed
     */
    public function create()
    {
        return View::make('shop::admin.banner.create');
    }

    /**
     * @param $id
     * @return mixed
     */
    public function edit($id)
    {
        $banner = Banner::findOrFail($id);
        return View::make('shop::admin.banner.edit', compact('banner'));
    }

    /**
     * @param $id
     * @return mixed
     */
    public function mark(Request $request)
    {
        if (!$id = $request->get('id')) {
            return ['status' => 'fail'];
        }
        $file = File::findOrFail($id);
        $file->from_storage = true;
        $file->save();
        return ['status' => 'success'];
    }

    /**
     * @param $id
     * @return mixed
     */
    public function destroy($id)
    {
        $banner = Banner::findOrFail($id);
        $banner->delete();

        return redirect()->route('admin.shop.banner.index')->with('success', 'Banner successfully deleted!');
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $banner = Banner::findOrFail($id);
        $banner->fill($request->all());

        if ($request->file('file')) {
            $banner->img = $this->saveFile($request);
        }
        $banner->save();

        return redirect()->route('admin.shop.banner.index')->with('success', 'Banner successfully updated');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {

        $banner = Banner::create($request->all());

        if ($request->file('file')) {
            $banner->img = $this->saveFile($request);
        }
        $banner->save();

        return redirect()->route('admin.shop.banner.index')->with('success', 'Banner successfully added');
    }

}

modules/Storage/Http/Controllers/Admin/UploadController.php
<?php namespace Modules\Storage\Http\Controllers\Admin;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Validator;
use Modules\Cms\Entities\File as FileEntity;
use Pingpong\Modules\Routing\Controller;

class UploadController extends Controller
{

    /**
     * Upload images
     *
     * @param Request $request
     * @return mixed
     */
    public function store(Request $request)
    {
        $rules = array(
            'file' => 'max:5000',
        );

        $validation = Validator::make($request->all(), $rules);

        if ($validation->fails()) {
            return Response::make($validation->errors->first(), 400);
        }

        $destinationPath = strtolower(sprintf("uploads/%s/", str_random(8)));

        if (!File::exists($destinationPath)) {
            File::makeDirectory($destinationPath, 0775, true);
        }
        $extension = $request->file('file')->getClientOriginalExtension(); // getting file extension
        $fileName = md5(uniqid()) . '.' . $extension; // renameing image
        $upload_success = $request->file('file')->move($destinationPath, $fileName); // uploading file to given path

        if ($upload_success) {
            $file = FileEntity::create(
                [
                    'path' => $destinationPath . $fileName,
                    'name' => $request->file('file')->getClientOriginalName(),
                    'title' => $request->file('file')->getClientOriginalName()
                ]
            );
            return Response::json(['fileId' => $file->id], 200);
        } else {
            return Response::json('error', 400);
        }
    }


}

modules/Storage/Http/Controllers/Front/StorageController.php
<?php namespace Modules\Storage\Http\Controllers\Front;

use App\Traits\SaveFileTrait;
use Illuminate\Http\Request;
use Modules\Storage\Entities\File;
use Pingpong\Modules\Routing\Controller;
use Illuminate\Support\Facades\View;

class StorageController extends Controller
{

    public function download($code)
    {
        $salt = File::DOWNLOAD_LINK_SALT;
        $file = File::whereRaw("MD5(CONCAT(id,'{$salt}')) = '$code'")->firstOrFail();
        $fPath = base_path('public/'.$file->path);
        if (!file_exists($fPath) || !is_readable($fPath)) {
            abort(404);
        }
        return response()->download(
            $fPath,
            $file->name
        );
    }

}

modules/Storage/Resources/views/index.blade.php
@extends('admin::layouts.master')

@section('content')
    <h1>Storage</h1>
    <div>
        <div class="col-md-12">
            <div class="col-md-10"></div>
            <div class="col-md-2">
                <button type="button" class="btn btn-success" data-toggle="modal" data-target=".bs-example-modal-lg">
                    Upload
                </button>
                @include('storage::modals.upload')
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>List files</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content col-md-12">
                        @foreach($files as $file)
                            <div class="col-md-3 storage-block">
                                @if (file_exists($file->path) && is_int(strpos(mime_content_type($file->path), 'image')))
                                 <img width="200" src="{{url($file->path)}}" alt="{{$file->title}}">
                                @else
                                 <img width="200" src="{{Theme::asset('image/storage_file.png')}}" alt="{{$file->title}}">
                                @endif
                                <div class="storage-img-nav">
                                    <button data-id="{{$file->id}}" class="cp-dwn-btn btn-xs btn-success">Copy download link</button>
                                    <button data-id="{{$file->id}}" class="cp-btn btn-xs  btn-info">Copy</button>
                                    <form class="entity-delete-form" method="POST"
                                          action="{{route('cms.image.destroy', ['id' => $file->id])}}">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                                        <button type="submit" class="entity-delete btn-xs  btn-danger">Delete
                                        </button>
                                    </form>
                                    <textarea  id="cp-btn-{{$file->id}}" class="cp-area">{{url($file->path)}}</textarea>
                                    <textarea  id="cp-dwn-btn-{{$file->id}}" class="cp-area">{{url('/storage/download/'.$file->getDownloadLink())}}</textarea>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
                <?php echo $files->render(); ?>

            </div>
        </div>
    @stop

    @section('javascript')
        <!-- chart js -->
            <script src="{{Module::asset('admin:js/chartjs/chart.min.js')}}"></script>
            <!-- bootstrap progress js -->
            <script src="{{Module::asset('admin:js/progressbar/bootstrap-progressbar.min.js')}}"></script>
            <script src="{{Module::asset('admin:js/nicescroll/jquery.nicescroll.min.js')}}"></script>
            <!-- dropzone -->
            <script src="{{Module::asset('admin:js/dropzone/dropzone.js')}}"></script>
            <script type="text/javascript">
                var uploadUrl = "{{ route('admin.storage.upload.store') }}";
                var token = "{{ csrf_token() }}";
                Dropzone.autoDiscover = false;
                var myDropzone = new Dropzone("div#myDrop", {
                    url: uploadUrl,
                    addRemoveLinks: true,
                    dictRemoveFile: 'Remove',
                    maxFilesize: 5,
                    params: {
                        _token: token,
                        from_storage: true
                    }
                });
                myDropzone.on("success", function (file, resp) {
                    if (resp.fileId) {
                        $.ajax({
                            type : 'post',
                            url: '{{route('admin.storage.storage.mark')}}',
                            data: {id: resp.fileId}
                        })

                    }
                });
                myDropzone.on("removedfile", function (file) {
                    $.ajax({
                        type: 'delete',
                        url: '{{route('cms.image.destroy')}}',
                        data: {id: file.uniqueId}
                    });

                });
                $('body').on('click', '.close, .modal-backdrop', function(){
                    window.location.reload()
                })
                $('.cp-btn').on('click', function (event) {
                    var id = $(this).attr('data-id');
                    console.log(id)
                    console.log('#cp-btn-' + id)
                    var copyTextarea = document.querySelector('#cp-btn-' + id);
                    copyTextarea.select();

                    try {
                        var successful = document.execCommand('copy');
                        var msg = successful ? 'successful' : 'unsuccessful';
                        console.log('Copying text command was ' + msg);
                    } catch (err) {
                        console.log('Oops, unable to copy');
                    }
                });
                $('.cp-dwn-btn ').on('click', function (event) {
                    var id = $(this).attr('data-id');
                    console.log(id)
                    console.log('#cp-dwn-btn-' + id)
                    var copyTextarea = document.querySelector('#cp-dwn-btn-' + id);
                    copyTextarea.select();

                    try {
                        var successful = document.execCommand('copy');
                        var msg = successful ? 'successful' : 'unsuccessful';
                        console.log('Copying text command was ' + msg);
                    } catch (err) {
                        console.log('Oops, unable to copy');
                    }
                });
            </script>

            <script>
                $('.storage-block').hover(
                    function () {
                        $(this).find('.storage-img-nav').show();
                    },
                    function () {
                        $(this).find('.storage-img-nav').hide();
                    }
                );
            </script>

        @stop
        @section('style')
            <link href="{{Module::asset('storage:css/style.css')}}" rel="stylesheet">
            <link href="{{Module::asset('admin:css/dropzone.css')}}" rel="stylesheet">
@stop