modules/Shop/Http/routes.php
<?php

#Admin
Route::group(['prefix' => 'admin', 'middleware' => ['admin.auth', 'admin.menu.storing'], 'namespace' => 'Modules\Shop\Http\Controllers'], function () {
    Route::group(['prefix' => 'shop', 'namespace' => 'Admin'], function () {
        Route::resource('attribute', 'AttributeController');
        Route::post('attribute/destroyOption', 'AttributeController@destroyOption');
        Route::resource('category', 'CategoryController');
        Route::resource('product_type', 'ProductTypeController');
        Route::resource('product', 'ProductController');
        Route::resource('brand', 'BrandController');
        Route::resource('comment', 'CommentController');
        Route::post('/comment/{id}/answer', ['as' => 'admin.shop.comment.answer', 'uses' => 'CommentController@answer']);
        Route::resource('order', 'OrderController');
        Route::controller('config', 'ConfigController');
        Route::resource('banner', 'BannerController');
        Route::resource('icon', 'IconController');
        Route::get('product/add/{productType}', ['as' => 'admin.shop.product.add', 'uses' => 'ProductController@add']);
        Route::get('product/{id}/copy', ['as' => 'admin.shop.product.copy', 'uses' => 'ProductController@copy']);
        Route::get('product-export', ['as' => 'admin.shop.product.export', 'uses' => 'ProductController@export']);
        Route::post('product-import', ['as' => 'admin.shop.product.import', 'uses' => 'ProductController@import']);
        Route::delete('product/{id}/delete-icon', ['as' => 'admin.shop.product.delete_icon', 'uses' => 'ProductController@deleteIcon']);
    });
});


#Front
Route::group(['prefix' => 'products', 'namespace' => 'Modules\Shop\Http\Controllers\Front'], function () {
    Route::get('/', ['as' => 'product.main', 'uses' => 'ProductController@main']);
    Route::get('/{category}/{naznachenie?}/{tsokol?}/{voltage?}', ['as' => 'product.index', 'uses' => 'ProductController@index']);

});
Route::get('/product/{code}', ['as' => 'product.show', 'uses' => 'Modules\Shop\Http\Controllers\Front\ProductController@show']);
Route::post('/product/{code}', 'Modules\Shop\Http\Controllers\Front\ProductController@showLendingAjax');
Route::post('/product/{id}/comment/add', ['as' => 'product.comment.add', 'uses' => 'Modules\Shop\Http\Controllers\Front\CommentController@create']);
Route::get('/product-comments/{offset?}', ['as' => 'product.comment.list', 'uses' => 'Modules\Shop\Http\Controllers\Front\CommentController@index']);
Route::get('/shop/search', ['as' => 'shop.search', 'uses' => 'Modules\Shop\Http\Controllers\Front\SearchController@search']);
Route::post('/shop/checkout/cart/{id}/add', ['as' => 'shop.checkout.cart.add', 'uses' => 'Modules\Shop\Http\Controllers\Front\CheckoutController@addProductToCart']);
Route::get('/shop/checkout/cart/{id}/delete', ['as' => 'shop.checkout.cart.delete', 'uses' => 'Modules\Shop\Http\Controllers\Front\CheckoutController@deleteProductFromCart']);
Route::get('/shop/checkout/cart', ['as' => 'shop.checkout.list', 'uses' => 'Modules\Shop\Http\Controllers\Front\CheckoutController@index']);
Route::get('/shop/checkout/data', ['as' => 'shop.checkout.cart.data', 'uses' => 'Modules\Shop\Http\Controllers\Front\CheckoutController@cartModalBody']);
Route::get('/shop/checkout/countable/{key}/{type}/{count}', ['as' => 'shop.checkout.countable', 'uses' => 'Modules\Shop\Http\Controllers\Front\CheckoutController@changeProductCount']);
Route::post('/shop/order/create', ['as' => 'shop.order.create', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@create']);
Route::post('/shop/order/one_click', ['as' => 'shop.order.oneclick', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@oneClick']);

Route::get('/api/v1/hotline/products', ['as' => 'api.shop.ec.hotline.products', 'uses' => 'Modules\Shop\Http\Controllers\Api\ExportController@hotlineProducts']);
Route::get('/api/v1/rozetka/products', ['as' => 'api.shop.ec.rozetka.products', 'uses' => 'Modules\Shop\Http\Controllers\Api\ExportController@rozetkaProducts']);


Route::get('/api/v1/merchant/products', ['as' => 'api.shop.merchant.products', 'uses' => 'Modules\Shop\Http\Controllers\Api\ExportController@merchantProducts']);

//Payment routes
Route::get('/shop/order/payment/{code}', ['as' => 'shop.order.payment.liqpay', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@liqPayPayment']);
Route::post('/shop/order/privat24/{code}', ['as' => 'shop.order.payment.privat24', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@privat24Payment']);
Route::get('/shop/order/payment-info/{code}', ['as' => 'shop.order.payment.payment_info', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@paymentInfo']);
Route::post('/shop/order/payment-info/{code}', ['as' => 'shop.order.payment.payment_info.post', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@paymentInfo']);
Route::post('/shop/order/liqpay-status', ['as' => 'shop.order.payment.liqpay_status', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@liqpayStatus']);



Route::post('/api/v1/tilda/form', ['as' => 'api.shop.tilda.form', 'uses' => 'Modules\Shop\Http\Controllers\Api\FormRequestController@postForm']);
Route::get('/api/v1/np/city', ['as' => 'api.shop.np.city', 'uses' => 'Modules\Shop\Http\Controllers\Api\NpController@city']);
Route::get('/api/v1/np/warehouse', ['as' => 'api.shop.np.warhouse', 'uses' => 'Modules\Shop\Http\Controllers\Api\NpController@warhouse']);
Route::any('/api/v1/form-request', ['as' => 'api.shop.formrequest', 'uses' => 'Modules\Shop\Http\Controllers\Api\FormRequestController@postForm']);
Route::post('/api/v1/form/subscribe', ['as' => 'api.shop.subscribe', 'uses' => 'Modules\Shop\Http\Controllers\Api\FormRequestController@postSubscribe']);

modules/Shop/Entities/Category.php
<?php namespace Modules\Shop\Entities;
   
use Illuminate\Database\Eloquent\Model;

/**
 * @property int|string code
 * @property mixed name
 */
class Category extends Model {

    protected $table = 'shop_category';
    protected $fillable = [
        'name',
        'code',
        'img',
        'description',
        'cms_meta_id',
        'filter',
        'visible',
        'parent_id',
        'show_in_main',
        'show_in_top',
        'sort',
    ];

    public function parents()
    {
        return $this->hasMany('Modules\Shop\Entities\Category', 'parent_id');

    }
    public function cjp()
    {
        return $this->hasMany(CategoryJoinProduct::class, 'shop_category_id')->orderBy('sort');;

    }

    public function meta()
    {
        return $this->belongsTo('Modules\Cms\Entities\Meta', 'cms_meta_id');
    }

    public function products()
    {
        return $this->belongsToMany(Product::class, 'shop_product_categories', 'shop_category_id', 'shop_product_id')
            ->orderBy('sort');
    }

    public function getChild()
    {
        return Category::where('parent_id', $this->id)->get();
    }

    public function getParent()
    {
        return Category::where('id', $this->parent_id)->first();
    }

}

modules/Shop/Http/Controllers/Admin/CategoryController.php
<?php namespace Modules\Shop\Http\Controllers\Admin;


use App\Http\Requests\Request;
use App\Traits\SaveFileTrait;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\View;
use Modules\Shop\Entities\CategoryJoinProduct;
use Modules\Shop\Http\Requests\CategoryRequest;
use Modules\Cms\Entities\Meta;
use Modules\Shop\Entities\Category;
use Illuminate\Support\Facades\File;
use Pingpong\Modules\Routing\Controller;

/**
 * @property string img
 */
class CategoryController extends Controller
{
    use SaveFileTrait;

    public function index()
    {
        $categories = Category::orderBy('parent_id', 'etc')->where('parent_id', null)->get();
        return View::make('shop::admin.category.list', compact('categories'));
    }

    public function create()
    {
        $categories = Category::all();

        return View::make('shop::admin.category.create', compact('categories'));
    }

    public function edit($id)
    {
        $categories = Category::all();
        $category = Category::with(['cjp', 'products'])->findOrFail($id);
        $category->cjp = $category->cjp->keyBy('shop_product_id');
        if (!$category->meta) {
            $category->meta = new Meta();
        }

        return View::make('shop::admin.category.edit', compact('category', 'categories'));
    }

    public function update(CategoryRequest $request, $id)
    {
        $postData = $request->all();

        if (!strlen($postData['parent_id'])) {
            unset($postData['parent_id']);
        }

        $category = Category::findOrFail($id);
        $category->fill($postData);
        if (!$category->meta) {
            $meta = Meta::create($postData);
            $category->meta()->associate($meta);
        } else {
            $category->meta->fill($postData);
            $category->meta->save();
        }

        if ($request->file('file')) {
            $category->img = $this->saveFile($request);
        }

        $category->save();

        if ($sort = $postData['category']['sort']??[]) {
            foreach ($sort as $product_id => $value) {
                \DB::table('shop_product_categories')
                    ->where(['shop_category_id' => $id, 'shop_product_id' => $product_id])
                    ->update(['sort' => $value]);
            }
        }

        return redirect()->back()->with('success', 'Category successfully updated!');
    }

    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        Category::where('parent_id', $id)->delete();
        $category->delete();
        return redirect()->route('admin.shop.category.index')->with('success', 'Category successfully deleted!');
    }

    public function store(CategoryRequest $request)
    {
        $postData = $request->all();
        if (!isset($postData['parent_id']) || !strlen($postData['parent_id'])) {
            unset($postData['parent_id']);
        }
        $category = Category::create($postData);
        $meta = Meta::create($postData);
        $category->meta()->associate($meta);

        if ($request->file('file')) {
            $category->img = $this->saveFile($request);
        }

        $category->save();

        return redirect()->back()->with('success', 'Category successfully added');
    }


}

modules/Shop/Resources/views/admin/category/list.blade.php
@extends('admin::layouts.master')

@section('content')

    <h1>Categories</h1>
    <div>
        <div class="col-md-12">
            <div class="col-md-10"></div>
            <div class="col-md-2">
                <a href="{{route('admin.shop.category.create')}}"><button class="btn btn-success">Create new category</button></a>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>List of categories</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <ul>
                            @foreach($categories as $category)
                                <?php addCategoryView($category, true); ?>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>

            <br />
            <br />
            <br />

        </div>
    </div>
@stop

@section('javascript')
    <!-- chart js -->
    <script src="{{Module::asset('admin:js/chartjs/chart.min.js')}}"></script>
    <!-- bootstrap progress js -->
    <script src="{{Module::asset('admin:js/progressbar/bootstrap-progressbar.min.js')}}"></script>
    <script src="{{Module::asset('admin:js/nicescroll/jquery.nicescroll.min.js')}}"></script>
    <!-- icheck -->
    <script src="{{Module::asset('admin:js/icheck/icheck.min.js')}}"></script>

    <!-- Datatables -->
    <script src="{{Module::asset('admin:js/datatables/js/jquery.dataTables.js')}}"></script>
    <script src="{{Module::asset('admin:js/datatables/tools/js/dataTables.tableTools.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('input.tableflat').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass: 'iradio_flat-green'
            });
        });

        var asInitVals = new Array();
        $(document).ready(function () {
            var oTable = $('#example').dataTable({
                "oLanguage": {
                    "sSearch": "Search all columns:"
                },
                "aoColumnDefs": [
                    {
                        'bSortable': false,
                        'aTargets': [0]
                    } //disables sorting for column one
                ],
                'iDisplayLength': 12,
                "sPaginationType": "full_numbers",
                "dom": 'T<"clear">lfrtip',
                "tableTools": {
                }
            });
            $("tfoot input").keyup(function () {
                /* Filter on the column based on the index of this element's parent <th> */
                oTable.fnFilter(this.value, $("tfoot th").index($(this).parent()));
            });
            $("tfoot input").each(function (i) {
                asInitVals[i] = this.value;
            });
            $("tfoot input").focus(function () {
                if (this.className == "search_init") {
                    this.className = "";
                    this.value = "";
                }
            });
            $("tfoot input").blur(function (i) {
                if (this.value == "") {
                    this.className = "search_init";
                    this.value = asInitVals[$("tfoot input").index(this)];
                }
            });
        });
    </script>
@stop
@section('style')
    <link href="{{Module::asset('admin:css/custom.css')}}" rel="stylesheet">
    <link href="{{Module::asset('admin:css/icheck/flat/green.css')}}" rel="stylesheet">
    <link href="{{Module::asset('admin:css/datatables/tools/css/dataTables.tableTools.css')}}" rel="stylesheet">
@stop