modules/Shop/Http/routes.php
<?php

#Admin
Route::group(['prefix' => 'admin', 'middleware' => ['admin.auth', 'admin.menu.storing'], 'namespace' => 'Modules\Shop\Http\Controllers'], function () {
    Route::group(['prefix' => 'shop', 'namespace' => 'Admin'], function () {
        Route::resource('attribute', 'AttributeController');
        Route::post('attribute/destroyOption', 'AttributeController@destroyOption');
        Route::resource('category', 'CategoryController');
        Route::resource('product_type', 'ProductTypeController');
        Route::resource('product', 'ProductController');
        Route::resource('brand', 'BrandController');
        Route::resource('comment', 'CommentController');
        Route::post('/comment/{id}/answer', ['as' => 'admin.shop.comment.answer', 'uses' => 'CommentController@answer']);
        Route::resource('order', 'OrderController');
        Route::controller('config', 'ConfigController');
        Route::resource('banner', 'BannerController');
        Route::resource('icon', 'IconController');
        Route::get('product/add/{productType}', ['as' => 'admin.shop.product.add', 'uses' => 'ProductController@add']);
        Route::get('product/{id}/copy', ['as' => 'admin.shop.product.copy', 'uses' => 'ProductController@copy']);
        Route::get('product-export', ['as' => 'admin.shop.product.export', 'uses' => 'ProductController@export']);
        Route::post('product-import', ['as' => 'admin.shop.product.import', 'uses' => 'ProductController@import']);
        Route::delete('product/{id}/delete-icon', ['as' => 'admin.shop.product.delete_icon', 'uses' => 'ProductController@deleteIcon']);
    });
});


#Front
Route::group(['prefix' => 'products', 'namespace' => 'Modules\Shop\Http\Controllers\Front'], function () {
    Route::get('/', ['as' => 'product.main', 'uses' => 'ProductController@main']);
    Route::get('/{category}/{naznachenie?}/{tsokol?}/{voltage?}', ['as' => 'product.index', 'uses' => 'ProductController@index']);

});
Route::get('/product/{code}', ['as' => 'product.show', 'uses' => 'Modules\Shop\Http\Controllers\Front\ProductController@show']);
Route::post('/product/{code}', 'Modules\Shop\Http\Controllers\Front\ProductController@showLendingAjax');
Route::post('/product/{id}/comment/add', ['as' => 'product.comment.add', 'uses' => 'Modules\Shop\Http\Controllers\Front\CommentController@create']);
Route::get('/product-comments/{offset?}', ['as' => 'product.comment.list', 'uses' => 'Modules\Shop\Http\Controllers\Front\CommentController@index']);
Route::get('/shop/search', ['as' => 'shop.search', 'uses' => 'Modules\Shop\Http\Controllers\Front\SearchController@search']);
Route::post('/shop/checkout/cart/{id}/add', ['as' => 'shop.checkout.cart.add', 'uses' => 'Modules\Shop\Http\Controllers\Front\CheckoutController@addProductToCart']);
Route::get('/shop/checkout/cart/{id}/delete', ['as' => 'shop.checkout.cart.delete', 'uses' => 'Modules\Shop\Http\Controllers\Front\CheckoutController@deleteProductFromCart']);
Route::get('/shop/checkout/cart', ['as' => 'shop.checkout.list', 'uses' => 'Modules\Shop\Http\Controllers\Front\CheckoutController@index']);
Route::get('/shop/checkout/data', ['as' => 'shop.checkout.cart.data', 'uses' => 'Modules\Shop\Http\Controllers\Front\CheckoutController@cartModalBody']);
Route::get('/shop/checkout/countable/{key}/{type}/{count}', ['as' => 'shop.checkout.countable', 'uses' => 'Modules\Shop\Http\Controllers\Front\CheckoutController@changeProductCount']);
Route::post('/shop/order/create', ['as' => 'shop.order.create', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@create']);
Route::post('/shop/order/one_click', ['as' => 'shop.order.oneclick', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@oneClick']);

Route::get('/api/v1/hotline/products', ['as' => 'api.shop.ec.hotline.products', 'uses' => 'Modules\Shop\Http\Controllers\Api\ExportController@hotlineProducts']);
Route::get('/api/v1/rozetka/products', ['as' => 'api.shop.ec.rozetka.products', 'uses' => 'Modules\Shop\Http\Controllers\Api\ExportController@rozetkaProducts']);


Route::get('/api/v1/merchant/products', ['as' => 'api.shop.merchant.products', 'uses' => 'Modules\Shop\Http\Controllers\Api\ExportController@merchantProducts']);

//Payment routes
Route::get('/shop/order/payment/{code}', ['as' => 'shop.order.payment.liqpay', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@liqPayPayment']);
Route::post('/shop/order/privat24/{code}', ['as' => 'shop.order.payment.privat24', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@privat24Payment']);
Route::get('/shop/order/payment-info/{code}', ['as' => 'shop.order.payment.payment_info', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@paymentInfo']);
Route::post('/shop/order/payment-info/{code}', ['as' => 'shop.order.payment.payment_info.post', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@paymentInfo']);
Route::post('/shop/order/liqpay-status', ['as' => 'shop.order.payment.liqpay_status', 'uses' => 'Modules\Shop\Http\Controllers\Front\OrderController@liqpayStatus']);



Route::post('/api/v1/tilda/form', ['as' => 'api.shop.tilda.form', 'uses' => 'Modules\Shop\Http\Controllers\Api\FormRequestController@postForm']);
Route::get('/api/v1/np/city', ['as' => 'api.shop.np.city', 'uses' => 'Modules\Shop\Http\Controllers\Api\NpController@city']);
Route::get('/api/v1/np/warehouse', ['as' => 'api.shop.np.warhouse', 'uses' => 'Modules\Shop\Http\Controllers\Api\NpController@warhouse']);
Route::any('/api/v1/form-request', ['as' => 'api.shop.formrequest', 'uses' => 'Modules\Shop\Http\Controllers\Api\FormRequestController@postForm']);
Route::post('/api/v1/form/subscribe', ['as' => 'api.shop.subscribe', 'uses' => 'Modules\Shop\Http\Controllers\Api\FormRequestController@postSubscribe']);

modules/Shop/Http/Controllers/Admin/OrderController.php
<?php namespace Modules\Shop\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\View;
use Modules\Shop\Entities\Order;
use Modules\Shop\Entities\Product;
use Pingpong\Modules\Routing\Controller;

class OrderController extends Controller {

	protected  $status = [
		'new','in_progress','processed','send_to_client','delivered','sold', 'canceled'
	];
	/**
	 * @return mixed
     */
	public function index()
	{
		$orders = Order::orderBy('id', 'desc')->get();
		return View::make('shop::admin.order.list', compact('orders'));
	}

	/**
	 * @param $id
	 * @return mixed
     */
	public function show($id)
	{
		$order = Order::findOrFail($id);
        $order->products[0]->getThumb();
        $delivery = json_decode($order->delivery);
		$status = $this->status;
		return View::make('shop::admin.order.show', compact('order', 'status', 'delivery'));
	}

	/**
	 * @param Request $request
	 * @param $id
	 * @return \Illuminate\Http\RedirectResponse
     */
	public function update(Request $request, $id)
	{
		$order = Order::findOrFail($id);
		$order->fill($request->get('order'));
		$order->save();

		return redirect()->back()->with('success', 'Order successfully updated');
	}
}

modules/Shop/Http/Controllers/Front/OrderController.php
<?php namespace Modules\Shop\Http\Controllers\Front;


use App\Jobs\SendOrdersRomax;
use Carbon\Carbon;
use Exception;
use GuzzleHttp\Client;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Modules\Cms\Entities\Meta;
use Modules\Cms\Entities\Page;
use Modules\Shop\Entities\Attribute;
use Modules\Shop\Entities\Order;
use Modules\Shop\Entities\Payment;
use Modules\Shop\Entities\Product;
use Modules\Shop\Http\Requests\OrderCreateRequest;
use Modules\Shop\Services\LiqPayService;
use Modules\Shop\Services\Private24Service;
use Modules\Shop\Utils\GA;
use Modules\Shop\Utils\Price\Processor;
use Pingpong\Modules\Routing\Controller;
use Pingpong\Themes\ThemeFacade;
use Pingpong\Themes\ThemeFacade as Theme;
use Sendpulse\RestApi\ApiClient;
use stdClass;

class OrderController extends Controller
{
    /**
     * @param OrderCreateRequest $request
     * @return $this|RedirectResponse
     */
    public function create(OrderCreateRequest $request)
    {
        try {
            $ga = new GA();
            if ($carts = $request->session()->get('shop.cart')) {
                $totalPrice = 0;
                $postData = $request->all();
                $postData['payment_type'] = Payment::PAYMENT_NAME_TYPE_MAP[$request->get('payment_type')] ?? Payment::PAYMENT_TYPE_NALICHNIE_TYPE;
                $delivery = new stdClass();
                switch ($postData['delivery']) {
                    case 's_np':
                        $delivery->type = 'novaya_pochta';
                        $delivery->city = $postData["s_np_city"];
                        $delivery->warehouse = $postData["s_np_warehouse"];
                        break;
                    case 'k_np':
                        $delivery->type = 'nova_poshta_address';
                        $delivery->city = $postData["k_np_city"];
                        $delivery->adress = $postData["k_np_adress"];
                        break;
                    default:
                        $delivery->type = 'samovivoz';
                        $delivery->city = $postData["s_shop_city"];
                        break;
                }
                $postData['delivery'] = json_encode($delivery);
                $postData['invoice'] = substr(strtoupper(uniqid()), 6);
                $postData['status'] = 'new';
                $order = Order::create($postData);
                $skus = [];
                foreach ($carts as $cart) {
                    $product = Product::with('brand')->findOrFail($cart['product_id']);
                    $selected = '';
                    if (!$cart['selected_options']) $cart['selected_options'] = [];
                    foreach ($cart['selected_options'] as $code => $value) {
                        $attribute = Attribute::where('code', $code)->first();
                        $selected .= $attribute->name . ': ' . $value . ' ';
                    }
                    $actualPrice = (new Processor())->calculate($product)->actualPrice();
                    $totalPrice += $actualPrice * $cart['count'];
                    $productsArray[] =
                        [
                            'shop_product_id' => $product->id,
                            'shop_order_id' => $order->id,
                            'price' => $actualPrice,
                            'count' => $cart['count'],
                            'selected' => $selected
                        ];
                    $p = new stdClass();

                    $productSendArray[] = (object)['product_id' => $product->romax_id, 'price' => $actualPrice * $cart['count'], 'count' => $cart['count']];

                    $gaProducts[] = [
                        'name' => $product->name,
                        'id' => $product->sku,
                        'price' => $actualPrice,
                        'brand' => $product->brand->name,
                        'quantity' => $cart['count'],
                    ];
                    $skus[] = $product->sku;
                    //add ordered
                    $product->count_ordered = $product->count_ordered + $cart['count'];
                    $product->save();
                }
                $order->total_price = $totalPrice;
                $order->save();
                $payment = null;
                if (in_array($request->get('payment'), [
                    Payment::PAYMENT_TYPE_PRIVAT_24_NAME,
                    Payment::PAYMENT_TYPE_VISA_MASTER_NAME,
                    Payment::PAYMENT_TYPE_INSTANT_INSTALLMENTS_NAME,
                    Payment::PAYMENT_TYPE_PART_INSTALLMENTS_NAME,

                ])) {
                    $payment = Payment::create([
                        'order_id' => $order->id,
                        'code' => md5(uniqid()),
                        'access_code' => microtime(true) . '_' . md5(uniqid()),
                        'payment_type' => Payment::PAYMENT_NAME_TYPE_MAP[$request->get('payment')],
                        'status' => Payment::STATUS_NEW,
                        'status_code' => 'no_status'
                    ]);
                }
                #$ga->addTransaction($productsArray,$order);
                DB::table('shop_products_orders')->insert(
                    $productsArray
                );
                //Payment
                if ($payment) {
                    if (in_array($payment->payment_type, [Payment::PAYMENT_TYPE_VISA_MASTER_TYPE, Payment::PAYMENT_TYPE_PRIVAT_24_TYPE])) {
                        $message = 'Вы успешно оформили заказ! Осталось только оплатить ваш заказ.';
                        $this->sendPuchaseMail($request, $postData);
                        $job = $this->dispatch(new SendOrdersRomax($order, $productSendArray));
                        $request->session()->remove('shop.cart');
                        return redirect()->route('shop.order.payment.liqpay', ['code' => $payment->access_code])
                            ->with('success', $message);
                    } elseif (in_array($payment->payment_type, [Payment::PAYMENT_TYPE_PART_INSTALLMENTS, Payment::PAYMENT_TYPE_INSTANT_INSTALLMENTS])) {
                        /** @var Private24Service $privateManager */
                        try {
                            $privateManager = app('private24');
                            $response = $privateManager->create($order, $request->get('payment_part_count', 2));
                            $payment->message = json_encode($response);
                            $payment->save();
                            $job = $this->dispatch(new SendOrdersRomax($order, $productSendArray));
                            $request->session()->remove('shop.cart');
                            return redirect()->away('https://payparts2.privatbank.ua/ipp/v2/payment?token=' . $response['token']);
                        } catch (Exception $e) {
                            throw $e;
                        }
                    }
                }
                event('shop.order.created', $order);

                $job = $this->dispatch(new SendOrdersRomax($order, $productSendArray));

                $request->session()->remove('shop.cart');
                $message = 'Ожидайте в ближайшее время звонка от оператора для подтверждения информации! Наш оператор обязательно перезвонит Вам для уточнения всех деталей!';
                if ($postData['payment'] == 'privat') {
                    $message = $message . '<p>Пока Вы ожидаете, Вы можете оплатить Ваш заказ на карточку ПриватБанка</p>';
                }
                if ($postData['payment'] == 'beznal') {
                    $message = $message . '<p>Безналичный способ оплаты подразумевает оплату на расчетный счет нашей компании. После связи с оператором Вам будет выставлен счет на оплату со всеми необходимыми документами.</p>';
                }

                try {
                    $api = app('esputnik');
                    $api->startEventAutomation360('rolcar_new_order', [
                        "phone" => $postData['phone'],
                        "email" => $postData['email'],
                        "name" => $postData['first_name'],
                        "payment" => $postData['payment'],
                        'order_invoice' => $order->invoice
                    ]);
                } catch (Exception $e) {

                }

                return Theme::view('shop.checkout.thank_you_page')
                    ->with('message', $message)
                    ->with('products', $gaProducts)
                    ->with('skus', $skus)
                    ->with('order', $order);
            }
        } catch (Exception $exception) {
            throw $exception;
            return redirect()->back()->withErrors('Ошибка при оформлении заказа.');
        }


    }

    public function liqPayPayment(string $code)
    {
        $payment = Payment::where([
            'access_code' => $code,
            'status' => Payment::STATUS_NEW
        ])->firstOrFail();
        $public_key = env('LP_PUBLIC_KEY');
        $private_key = env('LP_PRIVATE_KEY');
        $successUrl = route('shop.order.payment.payment_info', ['code' => $payment->access_code]);

        $liqpay = new LiqPayService($public_key, $private_key);
        $params = [
            'version' => 3,
            'action' => 'pay',
            'amount' => number_format($payment->order->total_price, 2, '.', ''),
            'currency' => 'UAH',
            'sender_first_name' => $payment->order->first_name,
            'info' => 'External information for payments #' . $payment->order->invoice,
            'description' => 'Оплата заказа № ' . $payment->order->invoice . '',
            'order_id' => 'Заказ №' . $payment->order->invoice,
            'result_url' => $successUrl,
            'server_url' => '/shop/order/liqpay-status',
            'language' => 'ru',

modules/Shop/Resources/views/admin/order/list.blade.php
@extends('admin::layouts.master')

@section('content')
    <h1>Order</h1>
    <div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>List of orders</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table id="example" class="table table-striped responsive-utilities jambo_table">
                            <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" class="tableflat">
                                </th>
                                <th>ID </th>
                                <th>Invoice</th>
                                <th>Name </th>
                                <th>Phone </th>
                                <th>Email </th>
                                <th>Status</th>
                                <th>Price</th>
                                <th>Created at</th>
                                <th class=" no-link last"><span class="nobr">Action</span>
                                </th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach($orders as $order)
                                <tr class="even pointer">
                                    <td class="a-center ">
                                        <input type="checkbox" class="tableflat">
                                    </td>
                                    <td>{{$order->id}}</td>
                                    <td>{{$order->invoice}}</td>
                                    <td>{{$order->first_name}}</td>
                                    <td>{{$order->phone}}</td>
                                    <td>{{$order->email}}</td>
                                    <td>
                                        @if ($order->status == 'new')
                                            <lable class="text-primary">{{trans("shop::admin.".$order->status )}}</lable>
                                        @elseif ($order->status == 'sold')
                                            <lable class="text-success">{{trans("shop::admin.".$order->status )}}</lable>
                                        @else
                                            <lable class="text-warning">{{trans("shop::admin.".$order->status )}}</lable>
                                        @endif
                                    </td>
                                    <td>{{$order->total_price}} uah</td>
                                    <td>{{$order->created_at}}</td>
                                    <td class=" last"><a href="{{route('admin.shop.order.show', ['id' => $order->id])}}">View</a></td>
                                </tr>
                            @endforeach

                            </tbody>

                        </table>
                    </div>
                </div>
            </div>

            <br />
            <br />
            <br />

        </div>
    </div>
@stop

@section('javascript')
    <!-- chart js -->
    <script src="{{Module::asset('admin:js/chartjs/chart.min.js')}}"></script>
    <!-- bootstrap progress js -->
    <script src="{{Module::asset('admin:js/progressbar/bootstrap-progressbar.min.js')}}"></script>
    <script src="{{Module::asset('admin:js/nicescroll/jquery.nicescroll.min.js')}}"></script>
    <!-- icheck -->
    <script src="{{Module::asset('admin:js/icheck/icheck.min.js')}}"></script>

    <!-- Datatables -->
    <script src="{{Module::asset('admin:js/datatables/js/jquery.dataTables.js')}}"></script>
    <script src="{{Module::asset('admin:js/datatables/tools/js/dataTables.tableTools.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('input.tableflat').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass: 'iradio_flat-green'
            });
        });

        var asInitVals = new Array();
        $(document).ready(function () {
            var oTable = $('#example').dataTable({
                "oLanguage": {
                    "sSearch": "Search all columns:"
                },
                "aoColumnDefs": [
                    {
                        'bSortable': false,
                        'aTargets': [0]
                    } //disables sorting for column one
                ],
                'iDisplayLength': 12,
                "sPaginationType": "full_numbers",
                "dom": 'T<"clear">lfrtip',
                "tableTools": {
                }
            });
            $("tfoot input").keyup(function () {
                /* Filter on the column based on the index of this element's parent <th> */
                oTable.fnFilter(this.value, $("tfoot th").index($(this).parent()));
            });
            $("tfoot input").each(function (i) {
                asInitVals[i] = this.value;
            });
            $("tfoot input").focus(function () {
                if (this.className == "search_init") {
                    this.className = "";
                    this.value = "";
                }
            });
            $("tfoot input").blur(function (i) {
                if (this.value == "") {
                    this.className = "search_init";
                    this.value = asInitVals[$("tfoot input").index(this)];
                }
            });
        });
    </script>
@stop
@section('style')
    <link href="{{Module::asset('admin:css/custom.css')}}" rel="stylesheet">
    <link href="{{Module::asset('admin:css/icheck/flat/green.css')}}" rel="stylesheet">
    <link href="{{Module::asset('admin:css/datatables/tools/css/dataTables.tableTools.css')}}" rel="stylesheet">
@stop

modules/Shop/Resources/views/admin/order/show.blade.php
@extends('admin::layouts.master')

@section('content')
    <h1>Order</h1>
    <div class="col-md-12">
        <div class="col-md-9"></div>
        <div c class="col-md-3 text-right">

            <a href="{{route('admin.shop.order.index')}}">
                <button type="button" class="btn btn-default">
                    Back
                </button>
            </a>


        </div>
    </div>
    <div class="">
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Order #{{$order->invoice}}</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content row">
                        <div class="col-md-6">
                            <div>Name: {{$order->last_name}} {{$order->first_name}}</div><br/>
                            <div>Phone: {{$order->phone}}</div><br/>
                            <div>E-mail: <a href="mailto:{{$order->email}}">{{$order->email}}</a></div><br/>                            
                        </div>
                        <div class="col-md-6">
                            <div>
                                <div><b>Доставка:</b></div>
                                <div style="padding-left: 20px">
                                    @if ( isset($delivery->type) )
                                        <div>Тип: {{$delivery->type}}</div> 
                                    @endif
                                    @if ( isset($delivery->city) )
                                        <div>Город: {{$delivery->city}}</div> 
                                    @endif
                                    @if ( isset($delivery->warehouse) )
                                        <div>склад НП: {{$delivery->warehouse}}</div> 
                                    @endif  
                                    @if ( isset($delivery->adress) )
                                        <div>Адрес: {{$delivery->adress}}</div> 
                                    @endif                                      
                                    </div>                                                             
                            </div>
                            <div><b>Оплата:</b> {{$order->payment}}</div>
                            <div><b>Промо код:</b> {{$order->promocode}}</div>
                            <div><b>Комментарий:</b> {{$order->description}}</div>
                        </div>


                        <table class="table" cellpadding="0" border="0" cellspacing="0">
                            @foreach( $order->orderDetails as $od )
                                <tr>
                                    <?php $photo = $od->product->photos ? $od->product->photos[0]->path : '';
                                    ?>
                                    <td><img class="product-thumb" src="{{ \Modules\Cms\Core\Images\ThumbBuilder::resize($photo , 'auto', 70) }}"/></td>
                                    <td  valign="top">
                                        <a href="{{route('product.show', ['code' => $od->product->code])}}" target="_blank">SKU: {{$od->product->sku}}
                                            <br />
                                            {{$od->product->name}} <br />
                                            Кол-во: {{$od->count}} <br />
                                            {{$od->selected}}
                                        </a>
                                    </td>
                                    <td  align="right" valign="top"><b>{{$od->product->price}} грн</b></td>
                                </tr>
                            @endforeach
                            <tr class="total">
                                <td></td>
                                <td width="80%" align="right" valign="top">Всего</td>
                                <td width="20%"  align="right" valign="top"><b>{{$order->total_price}} грн</b> </td>
                            </tr>
                        </table>
                    </div>

                    <form action="{{route('admin.shop.order.update', ['id' => $order->id])}}" method="POST">
                        <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                        <input type="hidden" name="_method" value="put"/>
                        <div class="col-md-6">
                            <label>Order status</label>
                            <select required name="order[status]" class="form-control">
                                <option></option>
                                @foreach($status as $s)
                                    <option @if($order->status == $s) selected @endif value="{{$s}}">{{trans("shop::admin.".$s)}}</option>
                                @endforeach
                            </select>
                            <br>
                            <button class="btn btn-primary" type="submit">Save</button>
                        </div>
                    </form>
                </div>

            </div>


        </div>
    </div>
@stop

@section('javascript')
    <!-- chart js -->
    <script src="{{Module::asset('admin:js/chartjs/chart.min.js')}}"></script>
    <!-- bootstrap progress js -->
    <script src="{{Module::asset('admin:js/progressbar/bootstrap-progressbar.min.js')}}"></script>
    <script src="{{Module::asset('admin:js/nicescroll/jquery.nicescroll.min.js')}}"></script>
    <!-- icheck -->
    <script src="{{Module::asset('admin:js/icheck/icheck.min.js')}}"></script>

    <!-- Datatables -->
    <script src="{{Module::asset('admin:js/datatables/js/jquery.dataTables.js')}}"></script>
    <script src="{{Module::asset('admin:js/datatables/tools/js/dataTables.tableTools.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('input.tableflat').iCheck({
                checkboxClass: 'icheckbox_flat-green',
                radioClass: 'iradio_flat-green'
            });
        });

        var asInitVals = new Array();
        $(document).ready(function () {
            var oTable = $('#example').dataTable({
                "oLanguage": {
                    "sSearch": "Search all columns:"
                },
                "aoColumnDefs": [
                    {
                        'bSortable': false,
                        'aTargets': [0]
                    } //disables sorting for column one
                ],
                'iDisplayLength': 12,
                "sPaginationType": "full_numbers",
                "dom": 'T<"clear">lfrtip',
                "tableTools": {
                }
            });
            $("tfoot input").keyup(function () {
                /* Filter on the column based on the index of this element's parent <th> */
                oTable.fnFilter(this.value, $("tfoot th").index($(this).parent()));
            });
            $("tfoot input").each(function (i) {
                asInitVals[i] = this.value;
            });
            $("tfoot input").focus(function () {
                if (this.className == "search_init") {
                    this.className = "";
                    this.value = "";
                }
            });
            $("tfoot input").blur(function (i) {
                if (this.value == "") {
                    this.className = "search_init";
                    this.value = asInitVals[$("tfoot input").index(this)];
                }
            });
        });
    </script>
@stop
@section('style')
    <link href="{{Module::asset('admin:css/custom.css')}}" rel="stylesheet">
    <link href="{{Module::asset('admin:css/icheck/flat/green.css')}}" rel="stylesheet">
    <link href="{{Module::asset('admin:css/datatables/tools/css/dataTables.tableTools.css')}}" rel="stylesheet">
@stop